### ISSUE TITLE
Get rid of deprecated dependency github.com/pkg/errors

### ISSUE THREAD

**Issue by alexandear** [incu6us/goimports-reviser#105]
[`github.com/pkg/errors`](https://github.com/pkg/errors) is archived and not maintained anymore since Go 1.13. See [StackOverflow answer](https://stackoverflow.com/questions/61933650/whats-the-difference-between-errors-wrapf-errors-errorf-and-fmt-errorf/61955455#61955455) for details.

The project still uses this deprecated package in `main.go`, `gen.go`, and `dir.go` files by calling `errors.WithStack`. Returned errors from these files are simple enough to track and understand. It's not needed to print an extended stack trace. So, we can rewrite to use native `errors` and `fmt.Errorf` and avoid using `github.com/pkg/errors`.

What do you think?

**Comment by incu6us** [comment]
yeah, I think it could be removed
