### ISSUE TITLE
Add ability to add named imports in a separate group

### ISSUE THREAD

**Issue by ustun-ed** [incu6us/goimports-reviser#116]
We have the following internal code style:

 - Standard library imports
-  repository imports
- Vendor imports
- Named imports (all internal and external named should be in same group)

Example:

```
import (
	"context"
	"fmt"
	"time"

	"github.com/ourcompany/ourcompany/pkg/log"
	"github.com/ourcompany/ourcompany/pkg/percentile"

        "github.com/google/go-cmp/cmp"

	svc "github.com/ourcompany/ourcompany/pkg/aggregator_service"
)
```

Could you add support for the final named imports group?

**Comment by ustun-ed** [comment]
Added a draft PR above.

**Comment by incu6us** [comment]
@n-oden added it
