### ISSUE TITLE
Getting error in formatting

### ISSUE THREAD

**Issue by mehdihadeli** [incu6us/goimports-reviser#118]
Hi,
At first, thanks for this useful package.
When I run this command, I get this error:
``` bash
goimports-reviser -rm-unused -set-alias -format -recursive ./...
```

Error:
``` bash
-: no Go files in \services\catalog_write_service
Failed to fix directory: failed to walk dif: failed to fix: package has an errors
```

**Comment by mehdihadeli** [comment]
My problem fixed by changing command to:
``` bash
goimports-reviser  ./... -rm-unused -set-alias -format -recursive
```

**Comment by incu6us** [comment]
@mehdihadeli it is not a fix. filepath, dir, or just file must be set in the end of the line. in other case, non of your params won’t be applied

**Comment by mehdihadeli** [comment]
@

**Comment by incu6us** [comment]
@mehdihadeli i'll fix it

**Comment by mehdihadeli** [comment]
Thanks

**Comment by danteay** [comment]
This happens to me with latest version using this command:

```bash
goimports-reviser -format -recursive ./...
```
response:

```bash
2023/08/22 08:41:12 Failed to fix directory: path is not a directory
```

version:

```bash
version: 3.4.1
build with: 
tag: v3.4.1
commit: 8ec65d10985bd9e317313a87071246fd985f10b3
source: https://github.com/incu6us/goimports-reviser

```

**Comment by incu6us** [comment]
closing the issue in case of fix made by @danteay

**Comment by mehdihadeli** [comment]
@incu6us Hi,
I still get the error for:
``` bash
goimports-reviser -rm-unused -set-alias -format -recursive ./...
```

``` bash
-: no Go files in
2023/09/15 13:12:39 Failed to fix directory ./...: failed to walk dif: failed to fix: package has an errors
```

**Comment by incu6us** [comment]
@mehdihadeli on of your package has an error. check your code

**Comment by mehdihadeli** [comment]
But it works fine without error with:

``` bash
goimports-reviser -format -recursive ./...
```

**Comment by incu6us** [comment]
Need to debug your code. Try to find a file with import which should be removed. Delete the import manually and  then check what is wrong

**Comment by mehdihadeli** [comment]
For example, I did format in [this microservice](https://github.com/mehdihadeli/go-ecommerce-microservices/tree/main/internal/services/catalog_read_service) in my project. I don't know why, could be related to remove some imports with _ ?

**Comment by incu6us** [comment]
it is known issue https://github.com/incu6us/goimports-reviser/issues/104. working on it

**Comment by mehdihadeli** [comment]
Yes, Maybe problem is here, because other things works

**Comment by incu6us** [comment]
added the feature to v3.5.5

**Comment by mehdihadeli** [comment]
@incu6us Thanks
