### ISSUE TITLE
not support ./... in m1 mac

### ISSUE THREAD

**Issue by Mr1X** [incu6us/goimports-reviser#123]
- os
> m1 mac  macos 13.2

- go version
> go version go1.21.0 darwin/arm64

- exec command
> goimports-reviser -rm-unused ./...

- command return 
> Failed to fix directory: path is not a directory

**Comment by chenyanchen** [comment]
I have the same problem with `goimports-reviser v3.4.1`, below command can do this:
```bash
goimports-reviser -recursive .
```

**Comment by incu6us** [comment]
issue should be fixed by related PR
