### ISSUE TITLE
error message in go version 1.21.0

### ISSUE THREAD

**Issue by crazytaxi824** [incu6us/goimports-reviser#127]
in go 1.21.0, `$ go mod init foo` will create a go.mod file with `go 1.21.0` in it, instead of `go 1.21`. in this case, goimports-reviser will show an error message:
```
go.mod:3: invalid go version '1.21.0': must match format 1.23
```

**Comment by incu6us** [comment]
this is an issue related to go: https://github.com/golang/go/issues/61851
