### ISSUE TITLE
go1.21: go.mod:3: invalid go version '1.21.0': must match format 1.23

### ISSUE THREAD

**Issue by ialidzhikov** [incu6us/goimports-reviser#129]
With go1.21 the module version has to be in format `X.Y.Z`. See https://github.com/golang/go/issues/62278 and https://github.com/dependabot/dependabot-core/issues/7895.

Trying to use 1.21.0 as module version

```
module github.com/foo/bar

go 1.21.0
```

fails with:
```
go.mod:3: invalid go version '1.21.0': must match format 1.23
```

**Comment by incu6us** [comment]
@ialidzhikov try to use v3.4.4. And reopen the issue in case of a problem

**Comment by ialidzhikov** [comment]
I see that v3.4.4 includes https://github.com/incu6us/goimports-reviser/pull/133. which only bumps the go version for the project. 

The issue report is about the cases when you run `goimports-reviser` against a module with go version directive in format `X.Y.Z`. For example
```
module github.com/foo/bar

go 1.21.0
```

`goimports-reviser` still fails with:
```
go.mod:3: invalid go version '1.21.0': must match format 1.23

Usage of goimports-reviser:

<Usage text is omitted>
```

Let me know if you need more detailed steps to reproduce.

> And reopen the issue in case of a problem

When a maintainer closes an issue, the reporter cannot open it. Can you please reopen it?

**Comment by incu6us** [comment]
As I see in the official documentation(https://go.dev/doc/modules/gomod-ref#module-syntax) the version must have format like `X.Y`.
<img width="1220" alt="image" src="https://github.com/incu6us/goimports-reviser/assets/7884395/d0e4d03d-f68b-431e-aa34-0a54082f6092">

Mentioned error message telling you that you are using wrong format(`...must match format 1.23`). So, in your case the string should be `go 1.21`

**Comment by ialidzhikov** [comment]
See https://go.dev/doc/toolchain#version:
> Before Go 1.21, the initial release of a Go toolchain was version 1.N, not 1.N.0, so for N < 21, the ordering is adjusted to place 1.N after the release candidates.

You can also check all the comments in https://github.com/golang/go/issues/62278. My understanding is that with go1.21 the expect format is `go X.Y.Z` and `go X.Y` refers to a development version of the `X.Y` version. So, `goimports-reviser` has to definitely support the `go X.Y.Z` format.

**Comment by incu6us** [comment]
fixed with new version `v3.4.5`:
<img width="872" alt="image" src="https://github.com/incu6us/goimports-reviser/assets/7884395/5c1b63a5-52cf-4c12-b189-58eb62e38331">

**Comment by ialidzhikov** [comment]
Thank you @incu6us !

[goimports-reviser@v3.4.5](https://github.com/incu6us/goimports-reviser/releases/tag/v3.4.5) resolves the issue.

**Comment by 2048Nemo** [comment]
I'm also having this issue, but I regenerated a go.mod file via  ```go mod init XXXX ```, the original go.mod file was generated in vscode, but I ran into problems opening it in goland

**Comment by incu6us** [comment]
@2048Nemo update the tool to the latest version
