### ISSUE TITLE
go.mod toolchain error

### ISSUE THREAD

**Issue by ozkansen** [incu6us/goimports-reviser#134]
Hi everyone, i got go 1.21 toolchain error.

go.mod file
```
module example

go 1.21

toolchain go1.21.0
```

error detail:
```sh
goimports-reviser -rm-unused -format ./...
```

output:
```text
go.mod:5: unknown directive: toolchain
```

**Comment by james-d-elliott** [comment]
How do you get this directive into the go mod using the standard tooling? It doesn't appear it's a documented directive for go.mod, only for go.work.

**Comment by james-d-elliott** [comment]
Ah looks like `go get toolchain` adds it. Unusual for a lack of docs.

**Comment by ozkansen** [comment]
When I updated the base go version in the project with `go mod tidy -go=1.21`, it added it automatically.

**Comment by ozkansen** [comment]
The error appears to be caused by the golang.org/x/mod package. I made the necessary updates and the problem was fixed.

**Comment by incu6us** [comment]
thanks @ozkansen 
could you fix issues in your PR to pass the pipeline

**Comment by incu6us** [comment]
thanks @ozkansen 
now issue is fixed
