### ISSUE TITLE
go command required, not found

### ISSUE THREAD

**Issue by jniewt** [incu6us/goimports-reviser#137]
Installed with snap and now I'm getting:

`Failed to fix file: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr:`

even though go (1.19) is in my $PATH.

**Comment by incu6us** [comment]
please, more details:
 - version of the tool;
 - cli command with all parameters;
 - full output

**Comment by jniewt** [comment]
Sorry. There you go:

version: 3.4.5
build with: 
tag: v3.4.5
commit: 607f2e628d899ae012894fcbd513d85cd65f0281
source: https://github.com/incu6us/goimports-reviser

Command: 
`/var/lib/snapd/snap/bin/goimports-reviser -rm-unused -company-prefixes foo.com -format -recursive .`

Output: 
`2023/09/14 15:07:07 Failed to fix directory .: failed to walk dif: failed to fix: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr:`

**Comment by incu6us** [comment]
what shows you:
- go version
- which go
- echo $PATH

?

**Comment by jniewt** [comment]
````
$ go version
go version go1.19.12 linux/amd64
$ which go
/usr/bin/go
$ echo $PATH
/home/foo/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/var/lib/snapd/snap/bin:/home/foo/go/bin:/home/foo/.local/share/JetBrains/Toolbox/scripts
```

**Comment by incu6us** [comment]
try to use:
```
PATH=$PATH:/usr/bin /var/lib/snapd/snap/bin/goimports-reviser -rm-unused -format -recursive .
```

**Comment by jniewt** [comment]
It's still the same error unfortunately.

**Comment by incu6us** [comment]
Your issue is related to configuration of your Snapd. Unfortunately, can't suggest what is wrong on your host with Snap. Reinstall the tool using go command
```
go install -v github.com/incu6us/goimports-reviser/v3@latest
```

**Comment by jniewt** [comment]
Any idea why this happens then?

```
$ go clean -modcache
$ go install -v github.com/incu6us/goimports-reviser/v3@latest
go: downloading github.com/incu6us/goimports-reviser/v3 v3.4.5
go: downloading github.com/incu6us/goimports-reviser v0.1.6
```
I can't seem to be able to get the right binary out of this, it doesn't even have the `-version` option. That's why I tried snap in the first place, because then at least I get the v3 binary.

**Comment by incu6us** [comment]
v1 is fetched because of linter package inside the project. it is ok. try to install the tool using `go` and run with version parameter

**Comment by incu6us** [comment]
my bad. don't use version if you're installing the tool using `go`. just use below line to install the latest version 
```
go install -v github.com/incu6us/goimports-reviser/v3@latest
```

**Comment by incu6us** [comment]
@jniewt have you had a chance to resolve it on you environment?

**Comment by jniewt** [comment]
No, sorry. I gave up and I'm using the old one. Whenever I install it with
go like you said it installs fine but when I run it it still seems to run
the old one and I can't find the reason for that. Or I assume it's the old
one because it doesn't have a -version option.

**Comment by incu6us** [comment]
@elbert-chan is it working from cli? not via your IDE?

**Comment by jniewt** [comment]
I removed all files concerning goimports-reviser from my system and installed it with: `go install -v github.com/incu6us/goimports-reviser/v3@latest`. The resulting binary still doesn't have the `-version` flag, but it doesn't complain anymore about go.mod containing `toolchain` keyword, so I don't know what to make of it. It seems I have the new version now...?

**Comment by incu6us** [comment]
> I removed all files concerning goimports-reviser from my system and installed it with: `go install -v github.com/incu6us/goimports-reviser/v3@latest` (from the terminal window within Goland IDE). The resulting binary still doesn't have the `-version` flag, but it doesn't complain anymore about go.mod containing `toolchain` keyword, so I don't know what to make of it. It seems I have the new version now...?

yes. it is the latest version

**Comment by hiyced** [comment]
@jniewt Have you solved your problem? I'm having the same issue.

**Comment by hiyced** [comment]
just solved my problem, need to add go/libexec to $PATH

> @jniewt Have you solved your problem? I'm having the same issue.

**Comment by jniewt** [comment]
I actually still have this problem on a completely new system. I'm on MacOS and I have go installed only through Goland so go env doesn't work outside of it, but it works in the Goland context and its terminal. I can also see the correct path to go sdk in $PATH within the goland terminal. I installed goimports-reviser using the Goland terminal with:

```
go install github.com/incu6us/goimports-reviser/v3@latest
```

 Nevertheless when I set up goimports-reviser as a file watcher it won't run:

```
/Users/<user>/go/bin/goimports-reviser -rm-unused -set-alias -format <absolute_file_path>
2025/01/30 08:57:10 Paths: [***]
2025/01/30 08:57:10 Processing ***
2025/01/30 08:57:10 Failed to fix file: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 
```

When I run the same command manually in the goland terminal it works.

I don't have this problem with any other file watchers.

**Comment by jniewt** [comment]
Found the solution. It is required to specify the Environment Variables for the watcher, e.g.:

```
GOROOT=$GOROOT$;GOPATH=$GOPATH$;PATH=$GoBinDirs$
```

**Comment by jniewt** [comment]
> [@jniewt](https://github.com/jniewt) Have you solved your problem? I'm having the same issue.

Sorry for some reason I don't get notifications from github so I missed the question and have also since then migrated to a new platform.

**Comment by denizgursoy** [comment]
I have the same problem
