### ISSUE TITLE
gRPC version higher than v1.59 failed

### ISSUE THREAD

**Issue by yeqown** [incu6us/goimports-reviser#151]
### Env

go version: 1.19
os: darwin/arm64

### Description

While my project contains the grpc versioned v1.61, goimports-reviser would faild with following message:

```bash
/Users/xxxx/.go/pkg/mod/google.golang.org/grpc@v1.60.1/internal/tcp_keepalive_unix.go:27:2: cannot find package
2024/03/05 16:58:51 Failed to fix file: package has an errors
```

I checked the file with the specified line which is
![image](https://github.com/incu6us/goimports-reviser/assets/27146233/ccbe63eb-0dab-4949-8c76-08beb1a36f76)

I also checked the package `golang.org/x/sys/unix` in the go module folder, it exists.

### Final fixed

I tried downgrade the gRPC to v1.59.0, the problem disappeared. Is this an issue of gRPC or [goimports-reviser](https://github.com/incu6us/goimports-reviser) ?

**Comment by incu6us** [comment]
seems, this is gRPC. the tool has no gRPC dependency
