### ISSUE TITLE
fails on package <name>_test that imports <name>

### ISSUE THREAD

**Issue by spikecurtis** [incu6us/goimports-reviser#158]
Our project includes go test files with package name `foo_test` in the same directory as `foo`, and these typically import the package to test it.  goimports-reviser incorrectly thinks this is an import cycle

e.g. 

```
agent/agent_test.go:49:2: could not import github.com/coder/coder/v2/agent (-: import cycle not allowed in test) (typecheck)
	"github.com/coder/coder/v2/agent"
	^
```

from https://github.com/coder/coder/blob/d04959cea8f24da12b7936f289ab0b268880a706/agent/agent_test.go#L49

**Comment by spikecurtis** [comment]
Sorry, getting wires crossed with a different tool!

**Comment by ccoVeille** [comment]
![z2smvh37sho01.jpg](https://github.com/incu6us/goimports-reviser/assets/3875889/dc44f968-72b9-49fb-97c8-75bd6fd3f93d)

https://www.reddit.com/r/ProgrammerHumor/comments/87r870/debugging/

@spikecurtis
