### ISSUE TITLE
Support for local and external project name

### ISSUE THREAD

**Issue by fgblomqvist** [incu6us/goimports-reviser#21]
When working on monorepos, it's not uncommon to reference your own project using both the external and the local path.

E.g.:
```go
import (
	"context"

	"github.com/3rdparty/dep"

	"coderepo.com/myproject/lib/versioned/pkg"
	"coderepo.com/myproject/lib/alsoversioned"

	"myproject/foo/bar"
	"myproject/foo/x"
)
```

Right now it's only possible to specify a single `project-name`. It would be neat if you could either specify both local and ext:
```
goimports-reviser -project-name foo -project-name-ext coderepo.com/myproject  -file-path $FilePath$
```

Or if you could generalize that parameter and make it something like this:
```
goimports-reviser -import-groups coderepo.com/myproject foo  -file-path $FilePath$
```
(which would order imports like this: std | 3rd-party | coderepo.com/myproject | foo)

or perhaps:
```
goimports-reviser -project-name foo -import-groups coderepo.com/myproject  -file-path $FilePath$
```
(which would order imports like this: std | 3rd-party | `<import groups in the order specified>` | foo)

What do you think?

What's achievable today is this:
```go
import (
	"context"

	"coderepo.com/myproject/lib/versioned/pkg"
	"coderepo.com/myproject/lib/alsoversioned"
	"github.com/3rdparty/dep"

	"myproject/foo/bar"
	"myproject/foo/x"
)
```
Which is ok but not ideal.

**Comment by incu6us** [comment]
Hi @fgblomqvist 
I like your idea. `goimports` has the same functionality with `-local` param. Will look into it...

**Comment by fgblomqvist** [comment]
Thanks. I took a look at your code and it seems fairly simple to add some support like this (as long as a decision is made in terms of what the feature should be). Let me know if you want help with a PR.

**Comment by incu6us** [comment]
check related PR, pls. If everything is OK, I will merge it

**Comment by incu6us** [comment]
the new release(v2.1.0) is ready to be installed via Brew, Snap or directly
