### ISSUE TITLE
Check project before local

### ISSUE THREAD

**Issue by fgblomqvist** [incu6us/goimports-reviser#23]
Been using goimports-reviser a lot since you added support for local, and it's been great. However, we did notice an issue that (I think) mainly applies to when you're working with monorepos.

**Scenario**
You have a monorepo which lives at `myproject.com/code/`.
One of the packages (`thispkg` in this example) refer to one of the other packages.

**Current outcome**
```
goimports-reviser -project-name myproject.com/code/thispkg -local myproject.com/code -file-path $FilePath$
```

```
context

github.com/3rdparty/pkg

myproject.com/code/foopkg
myproject.com/code/otherpkg
myproject.com/code/thispkg/stuff
myproject.com/code/thispkg/morestuff
```

**Desired outcome**
```
context

github.com/3rdparty/pkg

myproject.com/code/foopkg
myproject.com/code/otherpkg

myproject.com/code/thispkg/stuff
myproject.com/code/thispkg/morestuff
```

**Potential Solution**
Currently, [local is checked before project](https://github.com/incu6us/goimports-reviser/blob/master/reviser/reviser.go#L120). If those two are switched around, that should solve this problem and I don't think it would affect anything else. However, I'm open to other ideas/thoughts. Maybe we're doing something unorthodox with our package structure?

**Comment by fgblomqvist** [comment]
I'd be happy to submit a PR for this 🙂

**Comment by incu6us** [comment]
I think to change sorting order will give us another issue. Let me think on it a little bit

**Comment by incu6us** [comment]
@fgblomqvist Sorry for the delay(working on getting project name from go.mod). Did short PR with test for the desired outcome. Check pls. If everything is ok, let's merge it

**Comment by incu6us** [comment]
@fgblomqvist version 2.1.1 will cover the issue

**Comment by fgblomqvist** [comment]
Apologies, meant to take a look at it today, but yes the code looks great. Thank you so much for the effort! 🚀
