### ISSUE TITLE
Add option for automatically determining project name

### ISSUE THREAD

**Issue by fgblomqvist** [incu6us/goimports-reviser#24]
Or perhaps, if `-project-name` isn't specified, try to automatically determine it.

For modules (which I assume most people are using now), you just run `go list -m` anywhere inside that module (so it should be safe to run it in the same dir as the file you're trying to fix).

Might be possible to run it programmatically using something like `https://godoc.org/golang.org/x/tools/go/packages` as well.

**Comment by incu6us** [comment]
Package `https://godoc.org/golang.org/x/tools/go/packages` can't determine project name, btw I did custom solution that gives us the right behavior. Check version `2.2.0` without `-project-name` option

**Comment by fgblomqvist** [comment]
Looks great man, will test it out after the weekend. Thank you so much for all the effort! 😎 
(feel free to close this issue)

**Comment by fgblomqvist** [comment]
Just to report back: works flawlessly 🚀
