### ISSUE TITLE
Ability to output to stdout instead of writing file

### ISSUE THREAD

**Issue by fgblomqvist** [incu6us/goimports-reviser#28]
Would be handy at times to be able to only output formatted content to stdout rather than writing it to the file. This is the default behavior for `gofmt` and `goimports`. They only write the output if you pass `-w`.

This is useful when you try to integrate goimports-reviser into a larger toolchain (where another program might want to run goimports-reviser and use the output before writing it).

Would only need to add an extra cmd option and wrap [this section](https://github.com/incu6us/goimports-reviser/blob/2a888ec29a4e4cfa2b09df8263405a8d715f30d9/main.go#L142) in an if statement, more or less 😄 .

I can submit a PR for this (with tests) if you agree on it.

I guess the only question is whether you'd want to conform to the aforementioned formatters and only write if you pass `-w` (and therefore bump this to v3 since that's a breaking change), or if you just want to add an option for not writing and instead outputting to stdout (non-breaking change). Not sure what the latter option could be called.

**Comment by incu6us** [comment]
@fgblomqvist great idea! Sure, you could do it, but without breaking changes. Probably, would be better to add new option ‘-output’ with two values: ‘file’ and ‘stdout’. ‘file’ should be by default in case if option is not set. I think this approach wouldn’t brake other developers and give flexibility.

**Comment by incu6us** [comment]
@fgblomqvist merged. Version 2.3.0

**Comment by fgblomqvist** [comment]
Sweet, thanks!
