### ISSUE TITLE
syscall/js out of order when using WASM

### ISSUE THREAD

**Issue by darwayne** [incu6us/goimports-reviser#31]
Hello,

First and foremost thank you so much for building this awesome tool; I use it religiously.

**Issue**
I am using wasm with go and noticed that the `syscall/js` import isn't in the group i expected .. is this a bug?
  - I expected it to be in the first group

e.g
```golang
import (
	"fmt"
	"time"

	"github.com/lestrrat-go/jwx/jwt"
	"syscall/js"

	"github.com/darwayne/project/blah/blah"
	"github.com/darwayne/project/internal/blah"
)
```

**Comment by incu6us** [comment]
Which version of Go do you use?

**Comment by incu6us** [comment]
@darwayne which version of Go do you use?

**Comment by incu6us** [comment]
@darwayne try new version 2.3.1. It should work

**Comment by incu6us** [comment]
@darwayne have you managed to check the issue? can I close the ticket?

**Comment by incu6us** [comment]
@darwayne going to close the issue. The latest version should fix it, but if you'll have questions just ask

**Comment by darwayne** [comment]
oops only now seeing your messages. Yep this new update does the trick thanks for the quick turn around on this 🥇
