### ISSUE TITLE
return Error if linter detected errors in stdout mode.

### ISSUE THREAD

**Issue by yash97** [incu6us/goimports-reviser#47]
so while using this linter in ci we might need to return error if something is wrong and to not let linter modify file.

**Comment by jdechicchis** [comment]
I just got around to working on the `-format` option and looking at the code I think this can be done pretty easily by checking the `hasChange` value from [this line](https://github.com/incu6us/goimports-reviser/blob/master/main.go#L141). Any suggestions on a flag name? I can make a PR for this

**Comment by incu6us** [comment]
@jdechicchis could be something like `OptionLint` or `OptionPerformLint` or something other in those meaning. But it is about internal implementation. More useful - is to create external flag to prepare the check. Assuming something like `-lint` will be enough, but also, don't to forget about backward compatibility with previous flags

**Comment by yash97** [comment]
Suggestion from my side is make a boolean flag like `--error-on-change` .Also on the other hand can we get diff of change and present code and error.Because even if it will throw error we will not able to see specific lines where the error is.

**Comment by fgblomqvist** [comment]
@incu6us Do you have any further opinions on this? E.g. what would the output from `-lint` look like? I think it would be useful to have both a diff mode and a file-path mode. So maybe `-lint` and `-diff`?
The diff could be created using something like https://github.com/sergi/go-diff very easily.

**Comment by PradeepJigalur** [comment]
When this issue will be resolved?

**Comment by incu6us** [comment]
this is not an issue but enhancement. you could take a part into it and speedup the progress

**Comment by incu6us** [comment]
> When this issue will be resolved?

@PradeepJigalur  this is not an issue but enhancement. you could take a part into it and speedup the progress

**Comment by incu6us** [comment]
@fgblomqvist I think it is good idea to have `-diff`. About linter option I started work on huge refactoring to make it possible to use the tool with golangci-lint, so we don't need to any lint option here for now
