### ISSUE TITLE
Could not support mac m1 (arm)

### ISSUE THREAD

**Issue by azureskies** [incu6us/goimports-reviser#72]
MacBook-Pro librdkafka % brew tap incu6us/homebrew-tap 
brew install incu6us/homebrew-tap/goimports-reviser
==> Tapping incu6us/tap
Cloning into '/opt/homebrew/Library/Taps/incu6us/homebrew-tap'...
remote: Enumerating objects: 172, done.
remote: Counting objects: 100% (172/172), done.
remote: Compressing objects: 100% (127/127), done.
remote: Total 172 (delta 41), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (172/172), 21.90 KiB | 3.13 MiB/s, done.
Resolving deltas: 100% (41/41), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/incu6us/homebrew-tap/Formula/goimports-reviser.rb
formulae require at least a URL
Error: Cannot tap incu6us/tap: invalid syntax in tap!
==> Tapping incu6us/tap
Cloning into '/opt/homebrew/Library/Taps/incu6us/homebrew-tap'...
remote: Enumerating objects: 172, done.
remote: Counting objects: 100% (172/172), done.
remote: Compressing objects: 100% (127/127), done.
remote: Total 172 (delta 41), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (172/172), 21.90 KiB | 3.13 MiB/s, done.
Resolving deltas: 100% (41/41), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/incu6us/homebrew-tap/Formula/goimports-reviser.rb
formulae require at least a URL
Error: Cannot tap incu6us/tap: invalid syntax in tap!

**Comment by zhuxubin01** [comment]
the same problem

**Comment by james-d-elliott** [comment]
Try `go install github.com/incu6us/goimports-reviser/v2@latest` and then try to run it from the bin folder of the GOPATH?

**Comment by daregod** [comment]
A package installed this way does not support the `-version` flag

**Comment by daregod** [comment]
> A package installed this way does not support the `-version` flag

Ok, this can be solved with `GOBIN=/usr/local/bin go install -ldflags="-X 'main.Tag=v2.5.1'" github.com/incu6us/goimports-reviser/v2@v2.5.1`

**Comment by azureskies** [comment]
> > A package installed this way does not support the `-version` flag
> 
> Ok, this can be solved with `GOBIN=/usr/local/bin go install -ldflags="-X 'main.Tag=v2.5.1'" github.com/incu6us/goimports-reviser/v2@v2.5.1`

Nice it works for me, thank you very much.
