### ISSUE TITLE
Golang 1.18 and generics support

### ISSUE THREAD

**Issue by PaulAtFlexa** [incu6us/goimports-reviser#73]
Unfortunately as of now you cannot use this package against code with generics.  As far as I can tell, the package does work well with 1.18 code that does not use generics, but it is possible other features of this version I have not used also break the reviser.  

Error trace:

```
2022/05/31 17:29:01 115:33: expected '(', found '[' (and 10 more errors)
main.main
	/home/runner/work/goimports-reviser/goimports-reviser/main.go:175
runtime.main
	/opt/hostedtoolcache/go/1.14.15/x64/src/runtime/proc.go:203
runtime.goexit
	/opt/hostedtoolcache/go/1.14.15/x64/src/runtime/asm_amd64.s:1373
```

An example of the code that probably triggered this trace

```
func EqualableArraysEqual[T Equalable[T]](a1, a2 []T) bool {
        ...
}
```

**Comment by incu6us** [comment]
tool was updated to support go1.18. try new version v2.5.2
