### ISSUE TITLE
Add option to avoid modifying generated code

### ISSUE THREAD

**Issue by sgtsquiggs** [incu6us/goimports-reviser#81]
Currently we loop through all go files, grep to see if `"^// Code generated .* DO NOT EDIT\.$"` matches, and skip those files when applying goimports-reviser. An option to avoid these files would be preferable!

**Comment by gangming** [comment]
+1

**Comment by incu6us** [comment]
All generated files will be skipped by default. If you need to format generated file you can use `-apply-to-generated-files`-option.
version: v3.3.0
