### ISSUE TITLE
How to remove empty line in company and project

### ISSUE THREAD

**Issue by siskinc** [incu6us/goimports-reviser#88]
For example:
the command:
```bash
goimports-reviser -company-prefixes my_company -rm-unused -output stdout  -imports-order std,company,project,general -format ${file}
```

code:
```go
package main
import (
	"fmt"

	"my_company"
	
        "my_project"
)
```

expire
```go
package main
import (
	"fmt"

	"my_company"
        "my_project"
)
```

**Comment by incu6us** [comment]
hi @siskinc 
If you need to combine dependencies of your project and company you can use similar prefix of your organisation/company using `-company-prefixes`. 

Example:
`github.com/some_company/libs` - your company dependency repo
`github.com/some_company/my_project ` - your project
```
goimports-reviser -company-prefixes "github.com/some_company" ...
```
